### ISSUE TITLE
Propose local-storage as a save alternative

### ISSUE THREAD

**Issue by chambart** [rbardou/funweb#2]
You should propose a save method using local-storage as this has some advantages over cookies. It is not sent to the server, can be a lot bigger, and is easier to implement.

Js_of_ocaml api is: https://github.com/ocsigen/js_of_ocaml/blob/707cead7b6c3dfdd6ff113f59958b989ccdda6db/lib/dom_html.ml#L1215

See https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API for a general idea.

It is available in every browser since ages now, you shouldn't have problems with that.

**Comment by rbardou** [comment]
Very good idea, thanks for the links!

**Comment by rbardou** [comment]
Done.
